#!/bin/sh
git log --name-only --date=iso --reverse --pretty=format:%at "$@"\
| perl -00ln -e '($d,@f)=split/\n/;$d{$_}=$d for grep{-e}@f' \
             -e '}{utime undef,$d{$_},$_ for keys%d'
find -name '.git*' -prune -o -type d -exec sh -c 'touch -r $(ls -1rtd {}/* | tail -1) {}' \;
